#!/usr/bin/env python
"""Generate ``.env.example`` from ``Settings``.

WHY
    ``Settings`` uses ``extra="ignore"``, so a stale or misspelled variable in
    a hand-written ``.env.example`` is silently dead: it looks configured and
    does nothing. Generating the template from the model, and asserting parity
    in ``tests/unit/test_config.py``, makes that failure impossible.

USAGE
    python scripts/gen_env_example.py          # writes .env.example
    python scripts/gen_env_example.py --check  # exits 1 if it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from pydantic import SecretStr

from fde_assessment.common.config import Settings

REPO_ROOT = Path(__file__).resolve().parents[1]
TARGET = REPO_ROOT / ".env.example"

HEADER = """# Example configuration for the FDE assessment services.
#
# Generated by `python scripts/gen_env_example.py`, edit that script's
# section map, not this file, and never put a real secret here.
#
# The values below are the application defaults. The credentials are published
# development values: `Settings` refuses to start with APP_ENV=production while
# any of them is still in place.
"""

# Field name prefix -> section heading, in output order.
SECTIONS: list[tuple[str, tuple[str, ...]]] = [
    ("Application", ("app_env", "log_level", "log_format", "bind_host")),
    ("Service ports", ("mcp_gateway_port", "llm_gateway_port")),
    ("Persistence (Task 4 requires on-disk SQLite)", ("database_path",)),
    (
        "MCP security gateway (Task 2)",
        (
            "mcp_downstream_url",
            "mcp_downstream_timeout_ms",
            "mcp_gateway_max_body_bytes",
            "mcp_gateway_tokens",
            "admin_tool_prefix",
        ),
    ),
    (
        "LLM gateway identity and limits (Tasks 3 + 4)",
        (
            "llm_gateway_tenants",
            "api_key_pepper",
            "llm_gateway_max_body_bytes",
            "max_output_tokens",
            "max_prompt_chars",
        ),
    ),
    (
        "Model routing and fallback (Task 4)",
        (
            "primary_provider",
            "primary_model",
            "primary_timeout_ms",
            "secondary_provider",
            "secondary_model",
            "secondary_timeout_ms",
        ),
    ),
    (
        "Token-aware rate limiting (Task 4)",
        ("rate_limit_tokens", "rate_limit_window_seconds", "rate_limit_busy_timeout_ms"),
    ),
    ("Streaming PII guardrail (Task 3)", ("pii_carry_buffer_chars",)),
    (
        "Ollama -- optional local models, never used in CI",
        ("ollama_base_url", "ollama_model", "ollama_embedding_model"),
    ),
    (
        "RAG (Production Enhancement)",
        (
            "rag_embedding_provider",
            "rag_embedding_dim",
            "rag_chunk_size",
            "rag_chunk_overlap",
            "rag_default_top_k",
            "rag_max_top_k",
            "rag_max_context_chars",
        ),
    ),
]


def render_value(name: str) -> str:
    value = getattr(Settings(), name)
    if isinstance(value, SecretStr):
        return value.get_secret_value()
    if isinstance(value, Path):
        return str(value).replace("\\", "/")
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def render() -> str:
    known = set(Settings.model_fields)
    placed: set[str] = set()
    lines = [HEADER]

    for heading, fields in SECTIONS:
        lines.append(f"# --- {heading} " + "-" * max(0, 66 - len(heading)))
        for field in fields:
            if field not in known:
                raise SystemExit(f"scripts/gen_env_example.py references unknown field {field!r}")
            placed.add(field)
            lines.append(f"{field.upper()}={render_value(field)}")
        lines.append("")

    missing = sorted(known - placed)
    if missing:
        lines.append("# --- Unclassified (add these to SECTIONS) " + "-" * 30)
        lines.extend(f"{field.upper()}={render_value(field)}" for field in missing)
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if .env.example is stale")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            sys.stderr.write(".env.example is stale; run python scripts/gen_env_example.py\n")
            return 1
        sys.stdout.write(".env.example is up to date\n")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"wrote {TARGET.relative_to(REPO_ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
